import {
  ADMIN_TAXONOMY_MANAGE,
  ADMIN_USER_LOCATIONS_UPDATE,
  ADMIN_WORKFLOWS_MANAGE,
  COMMENT_ADD_PUBLIC,
  SUBTASK_CREATE,
  SUBTASK_TRANSITION_STATUS,
  SUBTASK_UPDATE,
  SUBTASK_VIEW,
  TICKET_ASSIGN_OWNER,
  TICKET_CREATE,
  TICKET_LIST_INBOX,
  TICKET_TRANSITION_STATUS,
  TICKET_UPDATE_CORE_FIELDS,
  TICKET_VIEW,
} from './capability-keys';

export const TicketCapabilities = [
  TICKET_CREATE,
  TICKET_VIEW,
  TICKET_LIST_INBOX,
  TICKET_TRANSITION_STATUS,
  TICKET_ASSIGN_OWNER,
  TICKET_UPDATE_CORE_FIELDS,
] as const;

export const SubtaskCapabilities = [
  SUBTASK_VIEW,
  SUBTASK_CREATE,
  SUBTASK_UPDATE,
  SUBTASK_TRANSITION_STATUS,
] as const;

export const CommentCapabilities = [COMMENT_ADD_PUBLIC] as const;

export const AdminCapabilities = [
  ADMIN_USER_LOCATIONS_UPDATE,
  ADMIN_WORKFLOWS_MANAGE,
  ADMIN_TAXONOMY_MANAGE,
] as const;
